### ISSUE TITLE
[suggestion] volume stuff

### ISSUE THREAD

**Issue by surytrap** [GAMINGNOOBdev/UltraRankSounds#1]
i think announcer volume slider should be kept independent of master slider so that you can even basically disable it mid-game too (there is already a setting for that but you get what i mean)

or make quieter if the soudns are too loud and you cant be bothered lowering all of them throuhg audacity

**Comment by GAMINGNOOBdev** [comment]
Thank you for the suggestion.
Volume will probably stay independent from the main volume slider in the settings (since i tried syncing it with in-game volume settings but it didn't really work out or fit well).
If the sounds themselves are too loud, there isn't honestly too much to do about it since there might be people who would want to customize their announcer sounds with earrape mp3's.
Marking this as closed now
